/**
 * Compiled ISO/IEC 38507:2022 pack artifacts (Pack #11).
 * Pack version 1.0.0 — organizational AI governance STANDARD (guidance).
 * Not legal authority; not a certification; not board-governance / GRC software.
 */

import type { PackProvenanceGraph } from '../../provenance.js';
import { POLICY_AUTHORITY_IDS } from '../../authority.js';

export type Iso38507CompiledRule = {
  rule_id: string;
  name: string;
  phase: 'input' | 'output';
  priority: number;
  conditions: Record<string, unknown>;
  decision: 'DENY' | 'ALLOW_WITH_CONTROLS' | 'REVIEW';
  reason_codes: string[];
  obligation_ids?: string[];
  control_ids?: string[];
  enigma_obligations?: string[];
  sources?: string[];
  derived_from?: string[];
  requirement_type?: string;
  note?: string;
};

export const ISO_38507_PACK_META = {
  pack_id: 'pack_iso_38507',
  pack_version: '1.0.0',
  input_interpreter: 'iso_38507_pack_v1' as const,
  output_interpreter: 'iso_38507_pack_v1_output' as const,
  input_policy_id: 'pol_iso_38507_input',
  input_version: 1,
  output_policy_id: 'pol_iso_38507_output',
  output_version: 1,
};

/**
 * ISO/IEC 38507-informed organizational AI governance controls.
 * Missing evidence → REVIEW (not DENY). Distinct from ISO 42001 management_system.
 */
export const ISO_38507_RULES: Iso38507CompiledRule[] = [
  {
    rule_id: 'ISO-38507-ACCOUNTABILITY-REVIEW',
    name: 'Review when governing-body AI accountability evidence is missing',
    phase: 'input',
    priority: 110,
    requirement_type: 'DERIVED_CONTROL',
    note: 'ISO/IEC 38507-informed organizational control — not ISO 38507 certification.',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      accountability: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_ACCOUNTABILITY_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-ACCOUNTABILITY'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-EXECUTIVE-ACCOUNTABILITY-REVIEW',
    name: 'Review when executive AI accountability evidence is missing',
    phase: 'input',
    priority: 105,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      executive_accountability: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_EXECUTIVE_ACCOUNTABILITY_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-EXECUTIVE'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-GOVERNANCE-DIRECTION-REVIEW',
    name: 'Review when AI governance direction evidence is missing',
    phase: 'input',
    priority: 100,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      governance_direction: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_GOVERNANCE_DIRECTION_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-DIRECTION'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-STRATEGIC-ALIGNMENT-REVIEW',
    name: 'Review when strategic AI alignment evidence is missing',
    phase: 'input',
    priority: 95,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      strategic_alignment: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_STRATEGIC_ALIGNMENT_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-ALIGNMENT'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-DECISION-RIGHTS-REVIEW',
    name: 'Review when AI decision-rights evidence is missing',
    phase: 'input',
    priority: 90,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Organizational decision rights ≠ Enigma AUTHORIZE for a held request.',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      decision_rights: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_DECISION_RIGHTS_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-DECISION-RIGHTS'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-OVERSIGHT-REVIEW',
    name: 'Review when AI oversight evidence is missing',
    phase: 'input',
    priority: 85,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      oversight: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_OVERSIGHT_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-OVERSIGHT'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-STAKEHOLDER-REVIEW',
    name: 'Review when relevant stakeholder identification evidence is missing',
    phase: 'input',
    priority: 80,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      stakeholder: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_STAKEHOLDER_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-STAKEHOLDER'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-STAKEHOLDER-IMPACT-REVIEW',
    name: 'Review when stakeholder impact consideration evidence is missing',
    phase: 'input',
    priority: 75,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Complements ISO 42005 impact assessment — does not replace it.',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      stakeholder_impact: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_STAKEHOLDER_IMPACT_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-STAKEHOLDER-IMPACT'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-HUMAN-ACCOUNTABILITY-REVIEW',
    name: 'Review when human accountability for AI outcomes evidence is missing',
    phase: 'input',
    priority: 70,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Organizational human accountability ≠ Enigma human resolution AUTHORIZE.',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      human_accountability: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_HUMAN_ACCOUNTABILITY_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-HUMAN-ACCOUNTABILITY'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-ESCALATION-REVIEW',
    name: 'Review when governance escalation-path evidence is missing',
    phase: 'input',
    priority: 65,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      escalation: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_ESCALATION_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-ESCALATION'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-GOVERNANCE-MONITORING-REVIEW',
    name: 'Review when AI governance monitoring/review evidence is missing',
    phase: 'input',
    priority: 60,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      governance_monitoring: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO38507_GOVERNANCE_MONITORING_REVIEW'],
    obligation_ids: ['ISO-38507-OBL-MONITORING'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-CONTROLS-SATISFIED',
    name: 'Allow with controls when ISO/IEC 38507-informed organizational governance evidence is established',
    phase: 'input',
    priority: 40,
    requirement_type: 'DERIVED_CONTROL',
    note: 'ISO/IEC 38507-informed posture — not ISO 38507 certified / compliant / scored.',
    conditions: {
      regulatory_applicability: 'ISO_38507',
      accountability: true,
      executive_accountability: true,
      governance_direction: true,
      strategic_alignment: true,
      decision_rights: true,
      oversight: true,
      stakeholder: true,
      stakeholder_impact: true,
      human_accountability: true,
      escalation: true,
      governance_monitoring: true,
    },
    decision: 'ALLOW_WITH_CONTROLS',
    reason_codes: ['ISO38507_CONTROLS_SATISFIED'],
    obligation_ids: [
      'ISO-38507-OBL-ACCOUNTABILITY',
      'ISO-38507-OBL-EXECUTIVE',
      'ISO-38507-OBL-DIRECTION',
      'ISO-38507-OBL-ALIGNMENT',
      'ISO-38507-OBL-DECISION-RIGHTS',
      'ISO-38507-OBL-OVERSIGHT',
      'ISO-38507-OBL-STAKEHOLDER',
      'ISO-38507-OBL-STAKEHOLDER-IMPACT',
      'ISO-38507-OBL-HUMAN-ACCOUNTABILITY',
      'ISO-38507-OBL-ESCALATION',
      'ISO-38507-OBL-MONITORING',
    ],
    control_ids: ['ctrl_audit_logging'],
    enigma_obligations: ['LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
  {
    rule_id: 'ISO-38507-OUTPUT-LOG',
    name: 'Log governance event for ISO/IEC 38507-scoped output',
    phase: 'output',
    priority: 50,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_38507',
    },
    decision: 'ALLOW_WITH_CONTROLS',
    reason_codes: ['ISO38507_OUTPUT_LOG'],
    obligation_ids: ['ISO-38507-OBL-MONITORING'],
    control_ids: ['ctrl_audit_logging'],
    enigma_obligations: ['LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_38507_2022'],
    derived_from: ['src_iso_38507_2022'],
  },
];

export const ISO_38507_PROVENANCE_GRAPH: PackProvenanceGraph = {
  sources: {
    src_iso_38507_2022: {
      source_id: 'src_iso_38507_2022',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      authority_type: 'STANDARD',
      legal_authority: false,
      authority_id: POLICY_AUTHORITY_IDS.iso38507,
      title:
        'Information technology — Governance of IT — Governance implications of the use of artificial intelligence by organizations',
      publisher: 'ISO / IEC',
      citation: 'ISO/IEC 38507:2022',
      canonical_url: 'https://www.iso.org/standard/56641.html',
      effective_date: '2022-04-08',
      retrieved_date: '2026-09-07',
      version: '2022',
      note: 'International Standard providing organizational AI governance guidance. Not statute; not an Enigma certification, compliance determination, board GRC product, or maturity score. Enigma-derived operational controls are interpretations for AI action governance evidence.',
    },
  },
  obligations: {
    'ISO-38507-OBL-ACCOUNTABILITY': {
      obligation_id: 'ISO-38507-OBL-ACCOUNTABILITY',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — governing body accountability'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-EXECUTIVE': {
      obligation_id: 'ISO-38507-OBL-EXECUTIVE',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — executive responsibility'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-DIRECTION': {
      obligation_id: 'ISO-38507-OBL-DIRECTION',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — governance direction'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-ALIGNMENT': {
      obligation_id: 'ISO-38507-OBL-ALIGNMENT',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — strategic alignment'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-DECISION-RIGHTS': {
      obligation_id: 'ISO-38507-OBL-DECISION-RIGHTS',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — decision rights'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-OVERSIGHT': {
      obligation_id: 'ISO-38507-OBL-OVERSIGHT',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — oversight'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-STAKEHOLDER': {
      obligation_id: 'ISO-38507-OBL-STAKEHOLDER',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — stakeholders'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-STAKEHOLDER-IMPACT': {
      obligation_id: 'ISO-38507-OBL-STAKEHOLDER-IMPACT',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — stakeholder considerations'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-HUMAN-ACCOUNTABILITY': {
      obligation_id: 'ISO-38507-OBL-HUMAN-ACCOUNTABILITY',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — human accountability'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-ESCALATION': {
      obligation_id: 'ISO-38507-OBL-ESCALATION',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — escalation'],
      source_ids: ['src_iso_38507_2022'],
    },
    'ISO-38507-OBL-MONITORING': {
      obligation_id: 'ISO-38507-OBL-MONITORING',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 38507:2022',
      authority_tier: 3,
      citations: ['ISO/IEC 38507:2022 — governance effectiveness'],
      source_ids: ['src_iso_38507_2022'],
    },
  },
};
