apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: '15s'
      httpMethod: 'POST'

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: node2ai-postgres:5432
    database: node2ai
    user: node2ai
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      timescaledb: false
