/**
 * Compiled OWASP Top 10 for LLM Applications 2025 pack artifacts (Pack #4).
 * Pack version 1.0.0 — focused SECURITY_GUIDANCE pack.
 * Not legal/regulatory authority; not a certification.
 */

import type { PackProvenanceGraph } from '../../provenance.js';
import { POLICY_AUTHORITY_IDS } from '../../authority.js';

export type OwaspCompiledRule = {
  rule_id: string;
  name: string;
  phase: 'input' | 'output';
  priority: number;
  conditions: Record<string, unknown>;
  decision: 'DENY' | 'ALLOW_WITH_CONTROLS' | 'REVIEW';
  reason_codes: string[];
  obligation_ids?: string[];
  control_ids?: string[];
  enigma_obligations?: string[];
  sources?: string[];
  derived_from?: string[];
  requirement_type?: string;
  note?: string;
};

export const OWASP_LLM_2025_PACK_META = {
  pack_id: 'pack_owasp_llm_2025',
  pack_version: '1.0.0',
  input_interpreter: 'owasp_llm_2025_pack_v1' as const,
  output_interpreter: 'owasp_llm_2025_pack_v1_output' as const,
  input_policy_id: 'pol_owasp_llm_2025_input',
  input_version: 1,
  output_policy_id: 'pol_owasp_llm_2025_output',
  output_version: 1,
};

/**
 * Evidence-based Enigma controls informed by OWASP LLM Top 10 2025.
 * Missing security-control evidence → REVIEW (no fabricated detectors).
 */
export const OWASP_LLM_2025_RULES: OwaspCompiledRule[] = [
  {
    rule_id: 'OWASP-LLM01-2025-PROMPT-INJECTION',
    name: 'Review when prompt-injection control evidence is not established',
    phase: 'input',
    priority: 100,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Enigma REVIEW informed by OWASP LLM01:2025 — not an injection detector.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      prompt_injection_controls: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM01_PROMPT_INJECTION_CONTROL_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM01-PROMPT-INJECTION'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM02-2025-SENSITIVE-INFORMATION-DISCLOSURE',
    name: 'Review when sensitive-data control evidence is not established',
    phase: 'input',
    priority: 95,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Security guidance control — does not duplicate HIPAA/Part 2 regulatory logic.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      sensitive_data_controls: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM02_SENSITIVE_DATA_CONTROL_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM02-SENSITIVE-DISCLOSURE'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM03-2025-SUPPLY-CHAIN',
    name: 'Review when supply-chain control evidence is not established',
    phase: 'input',
    priority: 90,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Attestation of supply-chain controls — Enigma does not inspect the supply chain.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      supply_chain_controls: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM03_SUPPLY_CHAIN_CONTROL_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM03-SUPPLY-CHAIN'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM04-2025-DATA-MODEL-POISONING',
    name: 'Review when poisoning-control evidence is not established',
    phase: 'input',
    priority: 85,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Does not determine whether a model was poisoned — evaluates declared control evidence.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      poisoning_controls: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM04_POISONING_CONTROL_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM04-POISONING'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM05-2025-IMPROPER-OUTPUT-HANDLING',
    name: 'Review when output-validation control evidence is not established',
    phase: 'input',
    priority: 80,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Enigma control informed by OWASP LLM05:2025 improper output handling guidance.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      output_validation_controls: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM05_OUTPUT_VALIDATION_CONTROL_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM05-OUTPUT-HANDLING'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM06-2025-EXCESSIVE-AGENCY',
    name: 'Review high-impact actions when agency-control evidence is not established',
    phase: 'input',
    priority: 110,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Applies to write/export/share/execute/transmit when OWASP is in scope.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      high_impact_agency: true,
      agency_controls: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM06_EXCESSIVE_AGENCY_CONTROL_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM06-AGENCY'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM07-2025-SYSTEM-PROMPT-LEAKAGE',
    name: 'Review when system-prompt protection evidence is not established',
    phase: 'input',
    priority: 75,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Enigma control informed by OWASP LLM07:2025 — not a prompt-leak scanner.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      system_prompt_protection: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM07_SYSTEM_PROMPT_PROTECTION_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM07-SYSTEM-PROMPT'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM08-2025-VECTOR-EMBEDDING-WEAKNESSES',
    name: 'Review when retrieval/embedding security evidence is not established',
    phase: 'input',
    priority: 70,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Does not inspect vector stores — evaluates declared retrieval security evidence.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      retrieval_security_controls: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM08_RETRIEVAL_SECURITY_CONTROL_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM08-RETRIEVAL'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM09-2025-MISINFORMATION',
    name: 'Review when grounding/misinformation-control evidence is not established',
    phase: 'input',
    priority: 65,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Does not fact-check model output — evaluates declared grounding controls.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      grounding_controls: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM09_GROUNDING_CONTROL_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM09-MISINFORMATION'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM10-2025-UNBOUNDED-CONSUMPTION',
    name: 'Review when resource-limit control evidence is not established',
    phase: 'input',
    priority: 60,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Evaluates declared resource limits — not live consumption metering.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      resource_limits: false,
    },
    decision: 'REVIEW',
    reason_codes: ['OWASP_LLM10_RESOURCE_LIMITS_CONTROL_REVIEW'],
    obligation_ids: ['OWASP-OBL-LLM10-UNBOUNDED-CONSUMPTION'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM-2025-CONTROLS-SATISFIED',
    name: 'Allow with logging when OWASP-informed security control evidence is established',
    phase: 'input',
    priority: 40,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Complementary Enigma logging when OWASP-informed control attestations are present.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
      prompt_injection_controls: true,
      sensitive_data_controls: true,
      supply_chain_controls: true,
      poisoning_controls: true,
      output_validation_controls: true,
      agency_controls: true,
      system_prompt_protection: true,
      retrieval_security_controls: true,
      grounding_controls: true,
      resource_limits: true,
    },
    decision: 'ALLOW_WITH_CONTROLS',
    reason_codes: ['OWASP_LLM_2025_CONTROLS_SATISFIED'],
    obligation_ids: [
      'OWASP-OBL-LLM01-PROMPT-INJECTION',
      'OWASP-OBL-LLM02-SENSITIVE-DISCLOSURE',
      'OWASP-OBL-LLM03-SUPPLY-CHAIN',
      'OWASP-OBL-LLM04-POISONING',
      'OWASP-OBL-LLM05-OUTPUT-HANDLING',
      'OWASP-OBL-LLM06-AGENCY',
      'OWASP-OBL-LLM07-SYSTEM-PROMPT',
      'OWASP-OBL-LLM08-RETRIEVAL',
      'OWASP-OBL-LLM09-MISINFORMATION',
      'OWASP-OBL-LLM10-UNBOUNDED-CONSUMPTION',
    ],
    control_ids: ['ctrl_audit_logging'],
    enigma_obligations: ['LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
  {
    rule_id: 'OWASP-LLM05-2025-OUTPUT-MONITOR-LOG',
    name: 'Log governance event for OWASP-scoped output handling',
    phase: 'output',
    priority: 50,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Complementary output logging informed by LLM05:2025 guidance.',
    conditions: {
      regulatory_applicability: 'OWASP_LLM_2025',
    },
    decision: 'ALLOW_WITH_CONTROLS',
    reason_codes: ['OWASP_LLM05_OUTPUT_MONITOR_LOG'],
    obligation_ids: ['OWASP-OBL-LLM05-OUTPUT-HANDLING'],
    control_ids: ['ctrl_audit_logging'],
    enigma_obligations: ['LOG_GOVERNANCE_EVENT'],
    sources: ['src_owasp_llm_top10_2025'],
    derived_from: ['src_owasp_llm_top10_2025'],
  },
];

export const OWASP_LLM_2025_PROVENANCE_GRAPH: PackProvenanceGraph = {
  sources: {
    src_owasp_llm_top10_2025: {
      source_id: 'src_owasp_llm_top10_2025',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      authority_type: 'SECURITY_GUIDANCE',
      legal_authority: false,
      authority_id: POLICY_AUTHORITY_IDS.owaspLlm2025,
      title: 'OWASP Top 10 for Large Language Model Applications 2025',
      publisher: 'OWASP Foundation / OWASP GenAI Security Project',
      citation: 'OWASP Top 10 for LLM Applications 2025',
      canonical_url: 'https://genai.owasp.org/llm-top-10/',
      effective_date: '2024-11-01',
      retrieved_date: null,
      version: '2025',
      note: 'Official OWASP GenAI Security Project publication. Security guidance — not statute or regulation.',
    },
  },
  obligations: {
    'OWASP-OBL-LLM01-PROMPT-INJECTION': {
      obligation_id: 'OWASP-OBL-LLM01-PROMPT-INJECTION',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM01:2025 Prompt Injection'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
    'OWASP-OBL-LLM02-SENSITIVE-DISCLOSURE': {
      obligation_id: 'OWASP-OBL-LLM02-SENSITIVE-DISCLOSURE',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM02:2025 Sensitive Information Disclosure'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
    'OWASP-OBL-LLM03-SUPPLY-CHAIN': {
      obligation_id: 'OWASP-OBL-LLM03-SUPPLY-CHAIN',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM03:2025 Supply Chain'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
    'OWASP-OBL-LLM04-POISONING': {
      obligation_id: 'OWASP-OBL-LLM04-POISONING',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM04:2025 Data and Model Poisoning'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
    'OWASP-OBL-LLM05-OUTPUT-HANDLING': {
      obligation_id: 'OWASP-OBL-LLM05-OUTPUT-HANDLING',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM05:2025 Improper Output Handling'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
    'OWASP-OBL-LLM06-AGENCY': {
      obligation_id: 'OWASP-OBL-LLM06-AGENCY',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM06:2025 Excessive Agency'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
    'OWASP-OBL-LLM07-SYSTEM-PROMPT': {
      obligation_id: 'OWASP-OBL-LLM07-SYSTEM-PROMPT',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM07:2025 System Prompt Leakage'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
    'OWASP-OBL-LLM08-RETRIEVAL': {
      obligation_id: 'OWASP-OBL-LLM08-RETRIEVAL',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM08:2025 Vector and Embedding Weaknesses'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
    'OWASP-OBL-LLM09-MISINFORMATION': {
      obligation_id: 'OWASP-OBL-LLM09-MISINFORMATION',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM09:2025 Misinformation'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
    'OWASP-OBL-LLM10-UNBOUNDED-CONSUMPTION': {
      obligation_id: 'OWASP-OBL-LLM10-UNBOUNDED-CONSUMPTION',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'OWASP Top 10 for LLM Applications 2025',
      authority_tier: 4,
      citations: ['OWASP LLM10:2025 Unbounded Consumption'],
      source_ids: ['src_owasp_llm_top10_2025'],
    },
  },
};
