apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node2ai-postgres-data
  namespace: node2ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node2ai-redis-data
  namespace: node2ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
