apiVersion: v1
kind: Service
metadata:
  name: {{ include "node2-enterprise.fullname" . }}-api
  labels:
    {{- include "node2-enterprise.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "node2-enterprise.selectorLabels" . | nindent 4 }}
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node2-enterprise.fullname" . }}-web
  labels:
    {{- include "node2-enterprise.labels" . | nindent 4 }}
    component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "node2-enterprise.selectorLabels" . | nindent 4 }}
    component: web
