/**
 * Compiled NIST CSF 2.0 pack artifacts (Pack #10).
 * Pack version 1.0.0 — cybersecurity FRAMEWORK (guidance).
 * Not legal authority; not a certification; not a cybersecurity score/SIEM.
 */

import type { PackProvenanceGraph } from '../../provenance.js';
import { POLICY_AUTHORITY_IDS } from '../../authority.js';

export type NistCsf2CompiledRule = {
  rule_id: string;
  name: string;
  phase: 'input' | 'output';
  priority: number;
  conditions: Record<string, unknown>;
  decision: 'DENY' | 'ALLOW_WITH_CONTROLS' | 'REVIEW';
  reason_codes: string[];
  obligation_ids?: string[];
  control_ids?: string[];
  enigma_obligations?: string[];
  sources?: string[];
  derived_from?: string[];
  requirement_type?: string;
  note?: string;
};

export const NIST_CSF_2_PACK_META = {
  pack_id: 'pack_nist_csf_2',
  pack_version: '1.0.0',
  input_interpreter: 'nist_csf_2_pack_v1' as const,
  output_interpreter: 'nist_csf_2_pack_v1_output' as const,
  input_policy_id: 'pol_nist_csf_2_input',
  input_version: 1,
  output_policy_id: 'pol_nist_csf_2_output',
  output_version: 1,
};

/**
 * NIST CSF 2.0-informed cybersecurity governance controls.
 * Missing evidence → REVIEW (not DENY). Six CSF Functions as evidence families.
 */
export const NIST_CSF_2_RULES: NistCsf2CompiledRule[] = [
  {
    rule_id: 'NIST-CSF-2-GOVERN-ACCOUNTABILITY-REVIEW',
    name: 'Review when cybersecurity accountability evidence is missing',
    phase: 'input',
    priority: 110,
    requirement_type: 'DERIVED_CONTROL',
    note: 'NIST CSF 2.0-informed GOVERN control — not NIST CSF certification.',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      govern_accountability: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_GOVERN_ACCOUNTABILITY_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-GOVERN-ACCOUNTABILITY'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-GOVERN-POLICY-REVIEW',
    name: 'Review when cybersecurity roles/policy evidence is missing',
    phase: 'input',
    priority: 105,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      govern_policy: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_GOVERN_POLICY_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-GOVERN-POLICY'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-IDENTIFY-ASSETS-REVIEW',
    name: 'Review when AI asset/dependency identification evidence is missing',
    phase: 'input',
    priority: 100,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      identify_assets: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_IDENTIFY_ASSETS_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-IDENTIFY-ASSETS'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-IDENTIFY-RISK-REVIEW',
    name: 'Review when cybersecurity risk identification evidence is missing',
    phase: 'input',
    priority: 95,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      identify_risk: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_IDENTIFY_RISK_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-IDENTIFY-RISK'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-PROTECT-ACCESS-REVIEW',
    name: 'Review when access/safeguard evidence is missing',
    phase: 'input',
    priority: 90,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      protect_access: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_PROTECT_ACCESS_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-PROTECT-ACCESS'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-PROTECT-DATA-REVIEW',
    name: 'Review when data-protection safeguard evidence is missing',
    phase: 'input',
    priority: 85,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      protect_data: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_PROTECT_DATA_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-PROTECT-DATA'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-DETECT-MONITORING-REVIEW',
    name: 'Review when cybersecurity monitoring evidence is missing',
    phase: 'input',
    priority: 80,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      detect_monitoring: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_DETECT_MONITORING_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-DETECT-MONITORING'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-DETECT-EVENTS-REVIEW',
    name: 'Review when cybersecurity event detection/logging evidence is missing',
    phase: 'input',
    priority: 75,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      detect_events: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_DETECT_EVENTS_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-DETECT-EVENTS'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-RESPOND-PLAN-REVIEW',
    name: 'Review when cybersecurity response-process evidence is missing',
    phase: 'input',
    priority: 70,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      respond_plan: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_RESPOND_PLAN_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-RESPOND-PLAN'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-RESPOND-COMMUNICATION-REVIEW',
    name: 'Review when incident communication evidence is missing',
    phase: 'input',
    priority: 65,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      respond_communication: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_RESPOND_COMMUNICATION_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-RESPOND-COMMUNICATION'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-RECOVER-PLAN-REVIEW',
    name: 'Review when recovery planning evidence is missing',
    phase: 'input',
    priority: 60,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      recover_plan: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_RECOVER_PLAN_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-RECOVER-PLAN'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-RECOVER-IMPROVEMENT-REVIEW',
    name: 'Review when recovery lessons-learned evidence is missing',
    phase: 'input',
    priority: 55,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      recover_improvement: false,
    },
    decision: 'REVIEW',
    reason_codes: ['NIST_CSF_2_RECOVER_IMPROVEMENT_REVIEW'],
    obligation_ids: ['NIST-CSF-2-OBL-RECOVER-IMPROVEMENT'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-CONTROLS-SATISFIED',
    name: 'Allow with controls when NIST CSF 2.0-informed cybersecurity evidence is established',
    phase: 'input',
    priority: 40,
    requirement_type: 'DERIVED_CONTROL',
    note: 'NIST CSF 2.0-informed posture — not NIST CSF certified / compliant / scored.',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
      govern_accountability: true,
      govern_policy: true,
      identify_assets: true,
      identify_risk: true,
      protect_access: true,
      protect_data: true,
      detect_monitoring: true,
      detect_events: true,
      respond_plan: true,
      respond_communication: true,
      recover_plan: true,
      recover_improvement: true,
    },
    decision: 'ALLOW_WITH_CONTROLS',
    reason_codes: ['NIST_CSF_2_CONTROLS_SATISFIED'],
    obligation_ids: [
      'NIST-CSF-2-OBL-GOVERN-ACCOUNTABILITY',
      'NIST-CSF-2-OBL-GOVERN-POLICY',
      'NIST-CSF-2-OBL-IDENTIFY-ASSETS',
      'NIST-CSF-2-OBL-IDENTIFY-RISK',
      'NIST-CSF-2-OBL-PROTECT-ACCESS',
      'NIST-CSF-2-OBL-PROTECT-DATA',
      'NIST-CSF-2-OBL-DETECT-MONITORING',
      'NIST-CSF-2-OBL-DETECT-EVENTS',
      'NIST-CSF-2-OBL-RESPOND-PLAN',
      'NIST-CSF-2-OBL-RESPOND-COMMUNICATION',
      'NIST-CSF-2-OBL-RECOVER-PLAN',
      'NIST-CSF-2-OBL-RECOVER-IMPROVEMENT',
    ],
    control_ids: ['ctrl_audit_logging'],
    enigma_obligations: ['LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
  {
    rule_id: 'NIST-CSF-2-OUTPUT-LOG',
    name: 'Log governance event for NIST CSF 2.0-scoped output',
    phase: 'output',
    priority: 50,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'NIST_CSF_2',
    },
    decision: 'ALLOW_WITH_CONTROLS',
    reason_codes: ['NIST_CSF_2_OUTPUT_LOG'],
    obligation_ids: ['NIST-CSF-2-OBL-DETECT-MONITORING'],
    control_ids: ['ctrl_audit_logging'],
    enigma_obligations: ['LOG_GOVERNANCE_EVENT'],
    sources: ['src_nist_csf_2_0'],
    derived_from: ['src_nist_csf_2_0'],
  },
];

export const NIST_CSF_2_PROVENANCE_GRAPH: PackProvenanceGraph = {
  sources: {
    src_nist_csf_2_0: {
      source_id: 'src_nist_csf_2_0',
      authority: 'NIST Cybersecurity Framework (CSF) 2.0',
      authority_tier: 4,
      authority_type: 'FRAMEWORK',
      legal_authority: false,
      authority_id: POLICY_AUTHORITY_IDS.nistCsf2,
      title: 'NIST CSWP 29 — The NIST Cybersecurity Framework (CSF) 2.0',
      publisher: 'National Institute of Standards and Technology',
      citation: 'NIST CSF 2.0 (CSWP 29)',
      canonical_url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20',
      effective_date: '2024-02-26',
      retrieved_date: '2026-09-07',
      version: '2.0',
      note: 'Voluntary cybersecurity framework. Not statute; not an Enigma certification, compliance determination, SIEM, or cybersecurity score. Enigma-derived operational controls are interpretations for AI governance evidence.',
    },
  },
  obligations: {
    'NIST-CSF-2-OBL-GOVERN-ACCOUNTABILITY': {
      obligation_id: 'NIST-CSF-2-OBL-GOVERN-ACCOUNTABILITY',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — GOVERN (GV)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-GOVERN-POLICY': {
      obligation_id: 'NIST-CSF-2-OBL-GOVERN-POLICY',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — GOVERN (GV)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-IDENTIFY-ASSETS': {
      obligation_id: 'NIST-CSF-2-OBL-IDENTIFY-ASSETS',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — IDENTIFY (ID)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-IDENTIFY-RISK': {
      obligation_id: 'NIST-CSF-2-OBL-IDENTIFY-RISK',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — IDENTIFY (ID)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-PROTECT-ACCESS': {
      obligation_id: 'NIST-CSF-2-OBL-PROTECT-ACCESS',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — PROTECT (PR)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-PROTECT-DATA': {
      obligation_id: 'NIST-CSF-2-OBL-PROTECT-DATA',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — PROTECT (PR)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-DETECT-MONITORING': {
      obligation_id: 'NIST-CSF-2-OBL-DETECT-MONITORING',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — DETECT (DE)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-DETECT-EVENTS': {
      obligation_id: 'NIST-CSF-2-OBL-DETECT-EVENTS',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — DETECT (DE)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-RESPOND-PLAN': {
      obligation_id: 'NIST-CSF-2-OBL-RESPOND-PLAN',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — RESPOND (RS)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-RESPOND-COMMUNICATION': {
      obligation_id: 'NIST-CSF-2-OBL-RESPOND-COMMUNICATION',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — RESPOND (RS)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-RECOVER-PLAN': {
      obligation_id: 'NIST-CSF-2-OBL-RECOVER-PLAN',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — RECOVER (RC)'],
      source_ids: ['src_nist_csf_2_0'],
    },
    'NIST-CSF-2-OBL-RECOVER-IMPROVEMENT': {
      obligation_id: 'NIST-CSF-2-OBL-RECOVER-IMPROVEMENT',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'NIST CSF 2.0',
      authority_tier: 4,
      citations: ['NIST CSF 2.0 — RECOVER (RC)'],
      source_ids: ['src_nist_csf_2_0'],
    },
  },
};
