/**
 * Compiled ISO/IEC 42005:2025 pack artifacts (Pack #8).
 * Pack version 1.0.0 — AI system impact-assessment STANDARD (guidance).
 * Not legal authority; not a certification; not an impact score.
 */

import type { PackProvenanceGraph } from '../../provenance.js';
import { POLICY_AUTHORITY_IDS } from '../../authority.js';

export type Iso42005CompiledRule = {
  rule_id: string;
  name: string;
  phase: 'input' | 'output';
  priority: number;
  conditions: Record<string, unknown>;
  decision: 'DENY' | 'ALLOW_WITH_CONTROLS' | 'REVIEW';
  reason_codes: string[];
  obligation_ids?: string[];
  control_ids?: string[];
  enigma_obligations?: string[];
  sources?: string[];
  derived_from?: string[];
  requirement_type?: string;
  note?: string;
};

export const ISO_42005_PACK_META = {
  pack_id: 'pack_iso_42005',
  pack_version: '1.0.0',
  input_interpreter: 'iso_42005_pack_v1' as const,
  output_interpreter: 'iso_42005_pack_v1_output' as const,
  input_policy_id: 'pol_iso_42005_input',
  input_version: 1,
  output_policy_id: 'pol_iso_42005_output',
  output_version: 1,
};

/**
 * ISO 42005-informed AI system impact-assessment controls.
 * Missing impact evidence → REVIEW (not DENY).
 * Distinct from ISO 42001 (AIMS) and ISO 23894 (risk management).
 */
export const ISO_42005_RULES: Iso42005CompiledRule[] = [
  {
    rule_id: 'ISO42005-R-IMPACT-SCOPE',
    name: 'Review when AI system impact-assessment scope is not defined',
    phase: 'input',
    priority: 100,
    requirement_type: 'DERIVED_CONTROL',
    note: 'ISO 42005-informed impact-assessment control — not ISO certification.',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      impact_scope_defined: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_IMPACT_SCOPE_REVIEW'],
    obligation_ids: ['ISO42005-OBL-IMPACT-SCOPE'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-STAKEHOLDERS',
    name: 'Review when affected stakeholders are not identified',
    phase: 'input',
    priority: 95,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      affected_stakeholders_identified: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_STAKEHOLDERS_REVIEW'],
    obligation_ids: ['ISO42005-OBL-STAKEHOLDERS'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-IMPACTS-IDENTIFIED',
    name: 'Review when potential impacts are not identified',
    phase: 'input',
    priority: 90,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Governance evidence — not an automatic impact classifier.',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      potential_impacts_identified: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_IMPACTS_IDENTIFIED_REVIEW'],
    obligation_ids: ['ISO42005-OBL-IMPACTS-IDENTIFIED'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-IMPACT-ASSESSMENT',
    name: 'Review when AI system impact assessment is not completed',
    phase: 'input',
    priority: 110,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Central impact-assessment evidence gate — completion ≠ automatic authorization.',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      impact_assessment_completed: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_IMPACT_ASSESSMENT_REVIEW'],
    obligation_ids: ['ISO42005-OBL-IMPACT-ASSESSMENT'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-IMPACT-SEVERITY',
    name: 'Review when impact severity has not been assessed',
    phase: 'input',
    priority: 85,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Evidence that severity was assessed — not an Enigma LOW/MEDIUM/HIGH scale.',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      impact_severity_assessed: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_IMPACT_SEVERITY_REVIEW'],
    obligation_ids: ['ISO42005-OBL-IMPACT-SEVERITY'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-IMPACT-LIKELIHOOD',
    name: 'Review when impact likelihood has not been assessed',
    phase: 'input',
    priority: 80,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      impact_likelihood_assessed: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_IMPACT_LIKELIHOOD_REVIEW'],
    obligation_ids: ['ISO42005-OBL-IMPACT-LIKELIHOOD'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-MITIGATIONS',
    name: 'Review when impact mitigations are not defined',
    phase: 'input',
    priority: 75,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      mitigations_defined: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_MITIGATIONS_REVIEW'],
    obligation_ids: ['ISO42005-OBL-MITIGATIONS'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-MITIGATIONS-IMPLEMENTED',
    name: 'Review when impact mitigations are not implemented',
    phase: 'input',
    priority: 70,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Declared mitigation ≠ Gateway enforcement proof.',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      mitigations_implemented: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_MITIGATIONS_IMPLEMENTED_REVIEW'],
    obligation_ids: ['ISO42005-OBL-MITIGATIONS-IMPLEMENTED'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-RESIDUAL-IMPACT',
    name: 'Review when residual impact has not been reviewed',
    phase: 'input',
    priority: 65,
    requirement_type: 'DERIVED_CONTROL',
    note: 'Organizational residual-impact review ≠ Enigma policy authorization.',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      residual_impact_reviewed: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_RESIDUAL_IMPACT_REVIEW'],
    obligation_ids: ['ISO42005-OBL-RESIDUAL-IMPACT'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-IMPACT-MONITORING',
    name: 'Review when impact monitoring is not established',
    phase: 'input',
    priority: 60,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      impact_monitoring_established: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_IMPACT_MONITORING_REVIEW'],
    obligation_ids: ['ISO42005-OBL-IMPACT-MONITORING'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-IMPACT-REVIEW',
    name: 'Review when impact review process is not established',
    phase: 'input',
    priority: 55,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      impact_review_established: false,
    },
    decision: 'REVIEW',
    reason_codes: ['ISO42005_IMPACT_REVIEW_PROCESS_REVIEW'],
    obligation_ids: ['ISO42005-OBL-IMPACT-REVIEW'],
    control_ids: ['ctrl_enigma_human_review'],
    enigma_obligations: ['REQUIRE_HUMAN_APPROVAL_FOR_EXECUTION', 'LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-CONTROLS-SATISFIED',
    name: 'Allow with controls when ISO 42005-informed impact evidence is established',
    phase: 'input',
    priority: 40,
    requirement_type: 'DERIVED_CONTROL',
    note: 'ISO 42005 policy posture — not ISO certified / impact score / automatic authorization.',
    conditions: {
      regulatory_applicability: 'ISO_42005',
      impact_scope_defined: true,
      affected_stakeholders_identified: true,
      potential_impacts_identified: true,
      impact_assessment_completed: true,
      impact_severity_assessed: true,
      impact_likelihood_assessed: true,
      mitigations_defined: true,
      mitigations_implemented: true,
      residual_impact_reviewed: true,
      impact_monitoring_established: true,
      impact_review_established: true,
    },
    decision: 'ALLOW_WITH_CONTROLS',
    reason_codes: ['ISO42005_CONTROLS_SATISFIED'],
    obligation_ids: [
      'ISO42005-OBL-IMPACT-SCOPE',
      'ISO42005-OBL-STAKEHOLDERS',
      'ISO42005-OBL-IMPACTS-IDENTIFIED',
      'ISO42005-OBL-IMPACT-ASSESSMENT',
      'ISO42005-OBL-IMPACT-SEVERITY',
      'ISO42005-OBL-IMPACT-LIKELIHOOD',
      'ISO42005-OBL-MITIGATIONS',
      'ISO42005-OBL-MITIGATIONS-IMPLEMENTED',
      'ISO42005-OBL-RESIDUAL-IMPACT',
      'ISO42005-OBL-IMPACT-MONITORING',
      'ISO42005-OBL-IMPACT-REVIEW',
    ],
    control_ids: ['ctrl_audit_logging'],
    enigma_obligations: ['LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
  {
    rule_id: 'ISO42005-R-OUTPUT-GOVERNANCE-LOG',
    name: 'Log governance event for ISO 42005-scoped output',
    phase: 'output',
    priority: 50,
    requirement_type: 'DERIVED_CONTROL',
    conditions: {
      regulatory_applicability: 'ISO_42005',
    },
    decision: 'ALLOW_WITH_CONTROLS',
    reason_codes: ['ISO42005_OUTPUT_GOVERNANCE_LOG'],
    obligation_ids: ['ISO42005-OBL-IMPACT-MONITORING'],
    control_ids: ['ctrl_audit_logging'],
    enigma_obligations: ['LOG_GOVERNANCE_EVENT'],
    sources: ['src_iso_iec_42005_2025'],
    derived_from: ['src_iso_iec_42005_2025'],
  },
];

export const ISO_42005_PROVENANCE_GRAPH: PackProvenanceGraph = {
  sources: {
    src_iso_iec_42005_2025: {
      source_id: 'src_iso_iec_42005_2025',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      authority_type: 'STANDARD',
      legal_authority: false,
      authority_id: POLICY_AUTHORITY_IDS.iso42005,
      title:
        'ISO/IEC 42005:2025 Information technology — Artificial intelligence (AI) — AI system impact assessment',
      publisher: 'ISO / IEC',
      citation: 'ISO/IEC 42005:2025',
      canonical_url: 'https://www.iso.org/standard/42005',
      effective_date: '2025-05-28',
      retrieved_date: null,
      version: '2025',
      note: 'International Standard providing guidance on AI system impact assessment. Edition 1, published 2025-05-28. Not statute; not Enigma certification or impact score.',
    },
  },
  obligations: {
    'ISO42005-OBL-IMPACT-SCOPE': {
      obligation_id: 'ISO42005-OBL-IMPACT-SCOPE',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Impact assessment scope'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-STAKEHOLDERS': {
      obligation_id: 'ISO42005-OBL-STAKEHOLDERS',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Affected individuals and societies'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-IMPACTS-IDENTIFIED': {
      obligation_id: 'ISO42005-OBL-IMPACTS-IDENTIFIED',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Identifying potential impacts'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-IMPACT-ASSESSMENT': {
      obligation_id: 'ISO42005-OBL-IMPACT-ASSESSMENT',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Performing AI system impact assessment'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-IMPACT-SEVERITY': {
      obligation_id: 'ISO42005-OBL-IMPACT-SEVERITY',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Evaluating impacts'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-IMPACT-LIKELIHOOD': {
      obligation_id: 'ISO42005-OBL-IMPACT-LIKELIHOOD',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Evaluating impacts'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-MITIGATIONS': {
      obligation_id: 'ISO42005-OBL-MITIGATIONS',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Addressing impacts'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-MITIGATIONS-IMPLEMENTED': {
      obligation_id: 'ISO42005-OBL-MITIGATIONS-IMPLEMENTED',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Addressing impacts'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-RESIDUAL-IMPACT': {
      obligation_id: 'ISO42005-OBL-RESIDUAL-IMPACT',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Documentation and review'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-IMPACT-MONITORING': {
      obligation_id: 'ISO42005-OBL-IMPACT-MONITORING',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Lifecycle considerations'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
    'ISO42005-OBL-IMPACT-REVIEW': {
      obligation_id: 'ISO42005-OBL-IMPACT-REVIEW',
      requirement_type: 'IMPLEMENTATION_OPTION',
      authority: 'ISO/IEC 42005:2025',
      authority_tier: 3,
      citations: ['ISO/IEC 42005:2025 — Documentation and review'],
      source_ids: ['src_iso_iec_42005_2025'],
    },
  },
};
